#!/usr/bin/env bash

function connect_mysql() {
    host=$1
    port=$2
    user=$3
    password=$4
    database=$5
    cmd=$6
    if [[ -z "${cmd}" ]]; then
        /usr/bin/mysql -h ${host} -P ${port} -u ${user} -p${password} ${database} -A
    else
        /usr/bin/mysql -h ${host} -P ${port} -u ${user} -p${password} ${database} --skip-column-names -s -e "${cmd}"
    fi
}

function connect_psql() {
    host=$1
    port=$2
    user=$3
    password=$4
    database=$5
    cmd=$6
    export PGPASSWORD=${password}
    if [ -z "${cmd}" ]; then
        psql -h ${host} -p ${port} -U ${user} -d ${database} -t -A
    else
        psql -h ${host} -p ${port} -U ${user} -d ${database} -t -A -F $'\t' -c "${cmd}"
    fi
}

function usage() {
    echo "usage: mconnect <datasource> [query]"
    echo "  datasource: 数据源"
    echo "  query:      执行命令"
    echo ""
    echo "example:"
    echo "  mconnect rta_mysql \"select 1\""
    echo ""
    echo "目前支持的数据源:"
    echo "  mob_adn:        Mobvista广告库"
    echo "  smartclick:     smartclick系统线下库"
    echo "  cutclick_mysql: 老掐量系统库"
    echo "  rta_mysql:      rta系统库"
    echo "  adn_report:     adn报表库"
    echo "  dsp_report:     dsp报表库"
    echo "  adn_portal:     adn日志库"
    echo "  sss_report:     3s报表库"
    echo "  sss_portal:     3s日志库"
}

function main() {
    case $1 in
        "mob_adn") connect_mysql adn-mysql-external.mobvista.com 3306 mob_adn_ro blueriver123 mob_adn "$2";;
        "smartclick") connect_mysql smartclick-offline.c5yzcdreb1xr.us-east-1.rds.amazonaws.com 3306 root Mobvista_smt123 smartclick "$2";;
        "cutclick_mysql") connect_mysql smartclick-online.c5yzcdreb1xr.us-east-1.rds.amazonaws.com 3306 mobdev Mobvista_123 "$2";;
        "rta_mysql") connect_mysql rta-mysql.c5yzcdreb1xr.us-east-1.rds.amazonaws.com 3306 badboy ab003765f3424bf8e2c8d1d69762d72c rta "$2";;
        "adn_report") connect_psql adndata-newup.cj0ro5bbcusg.us-east-1.redshift.amazonaws.com 5439 amosadn AmosMoBvIstA3579 adn_report "$2";;
        "dsp_report") connect_psql bj-dspdata.cj0ro5bbcusg.us-east-1.redshift.amazonaws.com 5439 dspdev PWY1xz8hcuTZvb data "$2";;
        "adn_portal") connect_psql adn-adserver.mobvista.com 5439 adndev ^NbGkcEATz1 data "$2";;
        "sss_report") connect_psql mbdatamining.ciglkwvshqzc.ap-southeast-1.redshift.amazonaws.com 5439 mob_tech Pr3j5KcQlM16 mob1log "$2";;
        "sss_portal") connect_psql portal-redshift-external.mobvista.com 5439 mob_tech Pr3j5KcQlM16 mob1log "$2";;
        *) usage;;
    esac
}

main "$@"
